# Generated by Django 4.1 on 2022-09-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=64)),
                ('sub_code', models.CharField(max_length=5)),
                ('semester', models.IntegerField(default=1)),
                ('year', models.IntegerField(default=2022)),
                ('max_seat', models.IntegerField(default=0)),
                ('seat', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('registered', models.ManyToManyField(blank=True, related_name='subjects', to='course.course')),
            ],
        ),
    ]
