# Generated by Django 4.1.1 on 2022-10-03 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0002_remove_enrollment_user_enrollment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="courses",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="course.course",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="user",
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
