# Generated by Django 4.1.1 on 2022-10-03 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0003_alter_enrollment_courses_alter_enrollment_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="enrollment", name="user",),
        migrations.AddField(
            model_name="enrollment",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
