name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Django unit tests
        run: |
          cd enrollment/enrollment
          pip install --user -r requirements.txt
          pip install coverage
          python -m pip install tk-tools
          python ./manage.py makemigrations
          python ./manage.py migrate
          coverage run ./manage.py test 
          coverage report -m